name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    strategy:
      matrix:
        go-version:
        - stable
        - oldstable
        runs-on:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
    - uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd
      with:
        version: v2.1.2
